### ISSUE TITLE
Question: Amending Template Hooks with Child Theme

### ISSUE THREAD

**Issue by JamieBradders** [propertyhive/honeycomb#1]
Hi there, I just wanted to start by thanking you for the awesome work with the honeycomb template and property hive plugin I'm finding it very useful so far!

I have a quick question regarding the honeycomb-template-hooks.php - I am trying to develop a child theme for the honeycomb template and have noticed that the structure of the homepage template is pieced together by the 'homepage' action in the template hooks file, I'm referring the following code:

```php
/**
 * Homepage
 *
 * @see  honeycomb_property_search_form()
 * @see  honeycomb_homepage_content()
 * @see  honeycomb_featured_properties()
 */
add_action( 'homepage', 'honeycomb_homepage_content',      	10 );
add_action( 'homepage', 'honeycomb_property_search_form',  	20 );
add_action( 'homepage', 'honeycomb_featured_properties',   	30 );
```

I simply want to replace the order of `honeycomb_homepage_content` and `honeycomb_property_search_form` so that the search form is first and homepage content is second in the hierarchy. When I try to take a copy of inc/honeycomb-template-hooks.php and place in the child theme directory my changes don't seem to be reflected, it seems to be defaulting to the honeycomb template hooks still.

Is there a way to get around this? I was under the impression that this would be overridden in the child theme but I'm guessing I was wrong. Any help or suggestions would be greatly appreciated.

Many thanks!
Jamie

**Comment by propertyhive** [comment]
Hi Jamie, 

Thanks for your kind words. You'll have to send me a link to the site when it's finished so I can take a look :)

With regards to your query I just added this to a child theme and it swapped the order of the contact and search form:

```
remove_action( 'homepage', 'honeycomb_property_search_form', 20 ); // Remove from original position of 20
add_action( 'homepage', 'honeycomb_property_search_form', 5 ); // Add it back with a higher priority
```

Hope that helps. Any issues just let me know, 
Steve

**Comment by JamieBradders** [comment]
Hey Steve, absolutely I'll keep you posted.

Thanks for the quick response, sorry just one more question, where is the preferred location for this code? Will functions.php suffice?

Jamie

**Comment by propertyhive** [comment]
Sure. functions.php in your child theme is perfect :)

**Comment by JamieBradders** [comment]
Okay sweet thanks again!
